import { ReactNode } from 'react'
import '../styles/globals.css'

export const metadata = {
  title: 'Metaversus',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='pt-BR'>
      <head>
        <link rel='preconnect' href='https://stijndv.com' />
        <link rel='stylesheet' href='https://stijndv.com/fonts/Eudoxus-Sans.css' />
      </head>
      <body>{children}</body>
    </html>
  )
}
